services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      target: build
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3080 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - /rails/vendor  # Prevent overriding vendor directory
    ports:
      - "3080:3080"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/toll_calculator_${RAILS_ENV:-development}
      POSTGRES_HOST: db
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_APP_CONFIG: /usr/local/bundle
    depends_on:
      - db
    stdin_open: true
    tty: true

  # cron:
  #   build: .
  #   command: cron -f
  #   volumes:
  #     - .:/app
  #     - bundle_cache:/usr/local/bundle
  #   environment:
  #     RAILS_ENV: ${RAILS_ENV:-development}
  #     DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/toll_calculator_${RAILS_ENV:-development}
  #     POSTGRES_HOST: db
  #   depends_on:
  #     - db
volumes:
  postgres_data:
  bundle_cache: