FROM ruby:3.4.1-slim

WORKDIR /rails

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    libjemalloc2 \
    libpq-dev \
    libvips \
    pkg-config \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set environment
ENV RAILS_ENV=development
ENV BUNDLE_PATH=/usr/local/bundle


# Install gems
COPY Gemfile Gemfile.lock ./

# Copy application
COPY . .

RUN bundle install


# Expose port
EXPOSE 3080

# Default command
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3080 -b '0.0.0.0'"]
