services:
  - type: web
    name: toll_calculator
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: toll_calculator_production
          property: connectionString

databases:
  - name: toll_calculator
    databaseName: toll_calculator_production
    ipAllowList: []
